
name: WASM

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download WASI SDK and BoringSSL
      run: |
        wget -q https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-24/wasi-sdk-24.0-x86_64-linux.tar.gz
        tar xf wasi-sdk-24.0-x86_64-linux.tar.gz
        git clone https://github.com/google/boringssl.git
    - name: Generate Boring WASM libs
      run: |
        ls
        cp boring-wasm/boring.h  wasi-sdk-24.0-x86_64-linux/share/cmake/
        cp boring-wasm/wasi-sdk-p2-boringssl.cmake  wasi-sdk-24.0-x86_64-linux
        WASI_SDK_PATH="$(pwd)/wasi-sdk-24.0-x86_64-linux"
        echo $WASI_SDK_PATH
        sudo apt-get install make
        cd boringssl/
        cmake -D"CMAKE_MAKE_PROGRAM:PATH=$(which make)" -DCMAKE_TOOLCHAIN_FILE=$WASI_SDK_PATH/share/cmake/wasi-sdk-p2-boringssl.cmake -B build -DCMAKE_BUILD_TYPE=Release
        make -C build crypto ssl
        ls build/
