
name: WASM

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Generate Boring WASM libs
      run: |
        wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-24/wasi-sdk-24.0-x86_64-linux.tar.gz
        tar xf wasi-sdk-24.0-x86_64-linux.tar.gz
        ls
